twitter:
  access_token: ~
  access_token_secret: ~
  api_key: ~
  api_secret: ~
  bearer_token: ~
imgur:
  client_id: ~
  client_secret: ~
reddit:
  client_id: ~
  client_secret: ~
  password: ~
  username: ~
  agent_name: ~
library_directory: post_library
saved_subreddits: ~
